### ISSUE TITLE
Select and download 1000 apps

### ISSUE THREAD

**Issue by kasnder** [privacy-tech-lab/gpc-android#71]
This would be important to get us started.

**Comment by n-aggarwal** [comment]
There are a couple of different ways we could partition our list. 


>Options:
>- collection (optional, defaults to collection.TOP_FREE): the Google Play collection that will be retrieved. Available options can be found [here](https://github.com/facundoolano/google-play-scraper/blob/b7669f78766b8306896447ddbe8797fe36eae49f/lib/constants.js#L67).
>- category (optional, defaults to no category): the app category to filter by. Available options can bee found [here](https://github.com/facundoolano/google-play-scraper/blob/b7669f78766b8306896447ddbe8797fe36eae49f/lib/constants.js#L10).
>- age (optional, defaults to no age filter): the age range to filter the apps (only for FAMILY and its subcategories). Available options are age.FIVE_UNDER, age.SIX_EIGHT, age.NINE_UP.
>- num (optional, defaults to 500): the amount of apps to retrieve.
>- lang (optional, defaults to 'en'): the two letter language code used to retrieve the applications.
>- country (optional, defaults to 'us'): the two letter country code used to retrieve the applications.
>- fullDetail (optional, defaults to false): if true, an extra request will be made for every resulting app to fetch its full detail.

There are [3 Collections](https://github.com/facundoolano/google-play-scraper/blob/b7669f78766b8306896447ddbe8797fe36eae49f/lib/constants.js#L67):
 - TOP_FREE: "TOP_FREE",
 - TOP_PAID: "TOP_PAID",
 - GROSSING: "GROSSING",

There are [54 Categories](https://github.com/facundoolano/google-play-scraper/blob/b7669f78766b8306896447ddbe8797fe36eae49f/lib/constants.js#L1): 
- APPLICATION: "APPLICATION",
- ANDROID_WEAR: "ANDROID_WEAR",
-  ART_AND_DESIGN: "ART_AND_DESIGN",
-  AUTO_AND_VEHICLES: "AUTO_AND_VEHICLES",
- And so on...

Either we could simply get the list of apps by Collection ("top free" and "top grossing"), or we can divide the list up by category, get "top free" and "top grossing" by each category. I am not sure which would be better. On one hand, simply getting the list by Collection gives us the most popular, most used apps; on the other hand, dividing by categories gives us in a way an extra control variable, so we can see if there are any significant differences across categories, although I am not sure what we could say about that.

I don't think we need to get a list of top paid apps for a couple of reasons: 
 1. Paid apps tend to not have ads
 2. They are not as popular as free apps (for obvious reasons).
 3. It would cause unnecessary overhead

Also,  do we want to touch on Apps designed for kids? Because I believe they have more strict guidelines than normal apps.

**Comment by SebastianZimmeck** [comment]
> Either we could simply get the list of apps by Collection ("top free" and "top grossing"), or we can divide the list up by category, get "top free" and "top grossing" by each category.

Either "top free" and/or "top grossing" works for me. What are the criteria for including and sorting apps in the "top free" list? Total downloads, current installs, something else ...?

> dividing by categories gives us in a way an extra control variable, so we can see if there are any significant differences across categories

I think that could be a nice extra dimension. Are there differences between app from different categories? So, if there are no other disadvantages (difficult to do, ...), getting an app set from each category could be nice. We could also do 1,000 top free + 50 apps from each category with some intersection of apps being in top free and the category sets.

> I don't think we need to get a list of top paid apps for a couple of reasons:

These are good reasons. I will also add the reason that they are paid. :) (If I recall correctly, you could return a paid app within some time period and get a refund; it may also be possible to get paid apps for free from some unofficial store, but I  would have doubts about such apps from such resource.)

We also should consider the option of one magnitude more, i.e., 10,000 apps. Whether we can pull it off depends on how intricate our analysis procedure ends up to be, how fast the analysis will be, which resources we need, ...

**Comment by SebastianZimmeck** [comment]
> So, once we have a list of apps in full detail, we can write a short program that uses an if statement to filter through the list as we desire!

That would be an option. 

I would say more in general, though, what matters is that we follow a methodological approach to create the app set. For example, if we wanted our app set to be representative of the Play Store population of apps, then we need to ensure that we not only download apps from just one category or one developer. 

Here are some criteria for selecting apps:
- Bigger apps (i.e., ones with more installs, downloads, ...) over smaller apps
- Newer apps over older apps(in particular, not stale apps that are no longer maintained)
- Only free apps
- US focus (i.e., apps that are big on the US Play Store)
- From different categories

Here is [one available list](https://www.androidrank.org/android-most-popular-google-play-apps?price=free) (not sure if that is the one we use because they do not show a date of when their ranking is current and the list has only 500 entries). But there may be other similar lists and services that create rankings. Most will be paid, e.g. [I believe this one is](https://app.sensortower.com/top-charts?os=android&category=all&device=), but maybe we can find a free one. 

We can also create our own list according to the criteria above (or others), but to my knowledge there is no filtering or ordering I know of on the Play Store for, say, the top 1,000 free apps according to download. So, we would need to come up with a strategy to approximate that.

We could also crawl app metadata for a large set, say, 10,000 or 100,000 apps according to some methodological criteria, and then select a subset from that set (e.g. top 50 from each category).

I would approach this task rather opportunistically, i.e., what is the easiest and quickest to do.

**Comment by wesley-tan** [comment]
I was just thinking whether there's any solution to automate the process of downloading the apks?  I was playing around with the JS and this python one (https://pypi.org/project/play-scraper/)
I tried something like this which goes through various categories and takes the top 50 of each category which I presume could be an 'easy' option but I think it may be not a good representative of the app store if we want a diversity of different categories like lifestyle etc. Seems to me that 'games' occupy a lot of categories.

`const gplay = require('google-play-scraper');

const categories = Object.values(gplay.category);
const collection = gplay.collection.TOP_FREE;  // Or any other collection you want
const appsPerCategory = 50;  // Number of apps to fetch per category

let totalApps = [];

const getApps = async () => {
  for (let i = 0; i < categories.length; i++) {
    // Stop if we already have 1000 apps
    if (totalApps.length >= 1000) break;

    try {
      const apps = await gplay.list({
        category: categories[i],
        collection: collection,
        num: appsPerCategory,
        fullDetail: false
      });

      totalApps = totalApps.concat(apps);

      // If we have more than 1000 apps, remove the excess
      if (totalApps.length > 1000) {
        totalApps = totalApps.slice(0, 1000);
      }
    } catch (err) {
      console.error(`Failed to fetch apps for category ${categories[i]}: `, err);
    }
  }

  return totalApps;
};

getApps().then(apps => console.log(apps));
`
Moving forward I think one possible approach could be listing the 200 categories we are thinking of and using TOP_FREE? I think this may be a tad 'manual' but it would guarantee that we have a good basket of apps

**Comment by n-aggarwal** [comment]
[apkeep](https://github.com/EFForg/apkeep) is CLI tool that provides a way to download apks. It can be used to with a bash script to automate the process.

[Platform Control- Token Dispenser](https://github.com/TrackerControl/platformcontrol-token-dispenser) may help to download Android Apps at scale.

**Comment by wesley-tan** [comment]
This is the setup I am trying (tried writing this in a style that would convert well to the `readme.md` later on):

**Step 1: Choose the Apps to Download**

**Use a tool like the Google Play Scraper on GitHub to help you with this. It will let you select the top 50 apps from each genre on the Play Store.**

- Go to the [[Google Play Scraper page on GitHub](https://github.com/facundoolano/google-play-scraper)](https://github.com/facundoolano/google-play-scraper)
- Follow the instructions to install and run the tool, and select the apps you want to download.

**Make sure to save the list of selected apps in a CSV file. Each line of the CSV file should contain one app ID.**

**Step 2: Install Necessary Tools**

**Before you can start downloading apps, you need to install some necessary tools. In this case, you will need to install apkeep and potentially other tools like Raccoon or Token Dispenser. Here are the steps to install apkeep:**

- First, install Rust by following the instructions on the [[Rust website](https://www.rust-lang.org/tools/install)](https://www.rust-lang.org/tools/install).

Open a terminal and run

```
cargo install apkeep 
```

to install apkeep.

- If you are using Android, install Termux first. You can do this by downloading it from the Play Store. Then, in Termux, run pkg update to upgrade to the latest packages. Finally, run `pkg install apkeep` to install apkeep.

If you decide to use other tools like Raccoon or Token Dispenser, you will need to follow the installation instructions on their respective GitHub pages. (I am still trying to figure out how to use TokenDispenser)

**Step 3: Download the Apps**

**Once you have the list of apps and have installed the necessary tools, you can start downloading the apps. Here is how you can use apkeep to download apps:**

- Open a terminal and navigate to the directory where you want to download the apps.
- Run the following command for each app ID in your CSV file:

```
apkeep -a <app-id> -d google-play -u '<your-email>@gmail.com' -p <your-password> .
```

**Replace <app-id> with the app ID from your CSV file, and <your-email>@gmail.com and <your-password> with your Google Play Store email and password.**

**Step 4: Handle Split APKs**

**If an app has a split APK, download all the APK files for that app. When you run the command to download an app with apkeep, it will tell you if there are additional APK files to download.**

- If there are additional APK files, run the same command as above, but append the architecture to the app ID. For example:

```
apkeep -a <app-id>:arm64-v8a -d google-play -u '<your-email>@gmail.com' -p <your-password>
```

**Comment by wesley-tan** [comment]
Using google-play-scraper, I created CSV files for the top 50 apps in the following 20 categories (totalling 1000 apps)

ART_AND_DESIGN
AUTO_AND_VEHICLES
BOOKS_AND_REFERENCE
BUSINESS
EDUCATION
ENTERTAINMENT
FINANCE
HEALTH_AND_FITNESS
MAPS_AND_NAVIGATION
MUSIC_AND_AUDIO
NEWS_AND_MAGAZINES
PRODUCTIVITY
SOCIAL
TRAVEL_AND_LOCAL
GAME_ACTION
GAME_EDUCATIONAL
GAME_SIMULATION
DATING
EVENTS
FAMILY

This is the script I used, changing the path (e.g. dating-apps.csv) and play.category (e.g. gplay.category.DATING) each time

```
const gplay = require('google-play-scraper');
const createCsvWriter = require('csv-writer').createObjectCsvWriter;  // you need to install csv-writer package

const csvWriter = createCsvWriter({
    path: 'dating-apps.csv', // change path each time
    header: [
        {id: 'appId', title: 'APP_ID'},
        {id: 'title', title: 'TITLE'},
        {id: 'developer', title: 'DEVELOPER'},
        {id: 'score', title: 'SCORE'},
    ],
});

gplay.list({
    category: gplay.category.DATING,
    collection: gplay.collection.TOP_FREE,
    num: 50
})
.then((apps) => {
    let data = apps.map(app => {
        return {
            appId: app.appId,
            title: app.title,
            developer: app.developer,
            score: app.score
        };
    });

    csvWriter.writeRecords(data)       // returns a promise
    .then(() => {
        console.log('...Done');
    });
});

```

**Comment by wesley-tan** [comment]
With regards to automating the process, I am currently facing some problems which I will be working on in the coming week.

Using the Rust and apkeep method, I repeatedly get the following error

```error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/wesleysimeontan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustl         _$LT$openssl..x509..X509VerifyResult$u20$as$u20$core..fmt..Display$GT$::fmt::hdfec200ca6d9b228 in libopenssl-2b7d39ae4fd85c04.rlib(openssl-2b7d39ae4fd85c04.openssl.ec35ac18-cgu.1.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)```
          

```error: could not compile `apkeep` (bin "apkeep") due to previous error
error: failed to compile `apkeep v0.15.0`, intermediate artifacts can be found at `/var/folders/34/xy0sgrqd32qb38yhrd81b1280000gn/T/cargo-installisWUSj````

Thus far, I've tried changing the SSL settings (e.g. brew install openssl) and changing the path (unset LC_ALL
unset PATH)

Using the Token Dispenser, I get the following error

```Traceback (most recent call last):
  File "/Users/wesleysimeontan/platformcontrol-token-dispenser/token_dispenser.py", line 37, in <module>
    with socketserver.TCPServer((HOST, PORT), TokenDispenser) as server:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use```

Thus far, I've tried updating the google-protobuf package and regenerating the googleplay_pb2.py file.
I will try different methods but the worst case is simply downloading the apps in the csv files manually through Raccoon, which I have tried.

**Comment by kasnder** [comment]
Weird that apkeep isn't working. Looks like an error with the openssl library? Maybe, raise an issue on the `apkeep` page with the details of the error?

As for the token dispenser, you'd need to kill python: `killall python` /  `killall python3`. But then, I'm not sure if `gplaycli` still works. I think that had some problems in the past.

**Comment by wesley-tan** [comment]
Also, I will document what exactly TOP FREE means (vs. TOP GROSSING or any other category)

**Comment by wesley-tan** [comment]
> Todo: It would be good to iterate over ALL the categories in the selection script, and to make sure to use a fake gmail.

Have done so, uploaded the updated files. This includes the following categories

```
const categories = [
  'GAME_ACTION',
  'GAME_ADVENTURE',
  'GAME_ARCADE',
  'GAME_BOARD',
  'GAME_CARD',
  'GAME_CASINO',
  'GAME_CASUAL',
  'GAME_EDUCATIONAL',
  'GAME_MUSIC',
  'GAME_PUZZLE',
  'GAME_RACING',
  'GAME_ROLE_PLAYING',
  'GAME_SIMULATION',
  'GAME_SPORTS',
  'GAME_STRATEGY',
  'GAME_TRIVIA',
  'GAME_WORD',
  'ART_AND_DESIGN',
  'AUTO_AND_VEHICLES',
  'BEAUTY',
  'BOOKS_AND_REFERENCE',
  'BUSINESS',
  'COMICS',
  'COMMUNICATION',
  'DATING',
  'EDUCATION',
  'ENTERTAINMENT',
  'EVENTS',
  'FINANCE',
  'FOOD_AND_DRINK',
  'HEALTH_AND_FITNESS',
  'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',
  'LIFESTYLE',
  'MAPS_AND_NAVIGATION',
  'MEDICAL',
  'MUSIC_AND_AUDIO',
  'NEWS_AND_MAGAZINES',
  'PARENTING',
  'PERSONALIZATION',
  'PHOTOGRAPHY',
  'PRODUCTIVITY',
  'SHOPPING',
  'SOCIAL',
  'SPORTS',
  'TOOLS',
  'TRAVEL_AND_LOCAL',
  'VIDEO_PLAYERS',
  'WEATHER'
];
```

**Comment by wesley-tan** [comment]
In the Top Free category, the apps with the most downloads that have a price of $0 make the list.

In the Top Paid category, the apps with the most downloads that have a price greater than $0 make the list.

The Top Grossing category lists the apps with the highest total revenue (that is, price * quantity sold + revenue from in-app purchases). 

Given that the Google Play Store lists up to the top 45 TOP_FREE per category, I have compiled the files of the top 40 TOP_FREE from each category

**Comment by SebastianZimmeck** [comment]
> In the Top Paid category, the apps with the most downloads that have a price greater than $0 make the list.

I do not think that it is necessary to create a list for paid apps since we can't get the APKs without paying (at least, through the official channels; to my knowledge there is a return option within a certain time period after buying an app, but that seems a bit dicey to me to do at scale; let me know if you have other information, @wesley-tan).

> Given that the Google Play Store lists up to the top 45 TOP_FREE per category, I have compiled the files of the top 40 TOP_FREE from each category

Why not the top 45 from each category then (or whatever number Google has per category; they do not need to be all the same; "whatever size Google's list is is a legitimate criterion)?

**Comment by wesley-tan** [comment]
I believe "whatever Google's list is" is actually >45, but only 45 appear on their visual interface when you go to Google Play etc. Thus, I think top 45 works as well! Looking at the past reports, some used numbers like 20, 30 etc. so I don't think it is a huge issue (the number always seems to be somewhat arbitrarily chosen)

And yes since we are downloading from the Play Store itself (and not just the .apk files online), we should just stick to `TOP_FREE`; some of the TOP_PAID and TOP_GROSSING apps are paid, so I think sticking to TOP_FREE is fine, above comment was just to give further clarity to the difference between TOP_FREE vs TOP_GROSSING

**Comment by wesley-tan** [comment]
As a personal note, following the use of apkeep, we could use an .sh file (something like this) to iterate through the various csv files that have been collated

```
#!/bin/bash
EMAIL='<your-email>@gmail.com'  # replace with your email
PASSWORD='<your-password>'  # replace with your password

# Read the CSV file
while IFS=$'\t' read -r APP_ID TITLE DEVELOPER SCORE
do
    # Skip the header
    if [ "$APP_ID" != "APP_ID" ]
    then
        echo "Downloading $TITLE..."
        apkeep -a $APP_ID -d google-play -u $EMAIL -p $PASSWORD .
    fi
done < apps-ART_AND_DESIGN.csv # replace the csv file
```

**Comment by kasnder** [comment]
Looks good to me. Looking forward to discussing!

**Comment by wesley-tan** [comment]
Just had a call with Nishant and the `apkeep` problem is fixed now! (It turned out to be a problem with downloading rust twice and likely some problem with the path and SSL)

I've also got the .sh to run and we can indeed automate the process of downloading the .apk! I tried with a few apps and categories. Namely, I used the ART_AND_DESIGN apps and ran this particular script

```
#!/bin/bash
EMAIL='<email>@gmail.com'  # replace with your email
PASSWORD='<password>'  # replace with your password

# Read the CSV file
while IFS=$',' read -r APP_ID TITLE DEVELOPER SCORE
do
    # Skip the header
    if [ "$APP_ID" != "APP_ID" ]
    then
        echo "Downloading App with ID $APP_ID, titled: $TITLE..."
        apkeep -a $APP_ID -d google-play -u $EMAIL -p $PASSWORD .
    fi
done < apps-ART_AND_DESIGN.csv # replace the csv file
```

This downloads in the same folder as your .sh file. I will place the .sh file in our `apps_csv` folder 

<img width="941" alt="Screenshot 2023-06-26 at 10 22 34 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/98197696/62228a32-d3b2-4580-9e2d-dcf75437179e">

Essentially, we can start easily downloading the apks we want :) We can discuss further tomorrow but this issue can be closed soon

**Comment by n-aggarwal** [comment]
@wesley-tan unfortunately the apks you provided me are not working. Most of them are crashing on the Pixel 6A. I have attached a few screenshots and screen recordings below showing the issue:
<img src=https://github.com/privacy-tech-lab/gpc-android/assets/121606501/75250d03-c013-42e0-b459-7bb5838ef9dd/ height=480 width=240>
<img src= https://github.com/privacy-tech-lab/gpc-android/assets/121606501/9a22953f-48ac-4463-9fab-a2467a5aff21 height=480 width=240>
<img src= https://github.com/privacy-tech-lab/gpc-android/assets/121606501/75f1a9b8-8bc1-4764-af01-e2271c2bec74 height=480 width=240>
<img src= https://github.com/privacy-tech-lab/gpc-android/assets/121606501/75f1a9b8-8bc1-4764-af01-e2271c2bec74 height=480 width=240>

**Comment by wesley-tan** [comment]
Oh no, I will try to figure out why this is the case asap.
The apks seem to work for emulator, I will try with my phone but could it be an issue with the rooted phone or settings?

Uploading Screen Recording 2023-07-03 at 9.00.05 PM.mov…

**Comment by SebastianZimmeck** [comment]
@wesley-tan, please make sure that the APKs work for a Pixel 6a, which can be easily tested on an emulator.

@n-aggarwal, what is the Android version you have installed?

**Comment by n-aggarwal** [comment]
I have android 13 installed on the Pixel 6A

**Comment by kasnder** [comment]
Make sure we download complete split apps, including architecture for `arm64`.

**Comment by kasnder** [comment]
It seems that `apkeep` has a `split_apk` option: when set to 1 or true, this attempts to download a split apk.

**Comment by SebastianZimmeck** [comment]
Any news @wesley-tan?

**Comment by wesley-tan** [comment]
I tried using the method above

```
# Read the CSV file
while IFS=$',' read -r APP_ID TITLE DEVELOPER SCORE
do
    # Skip the header
    if [ "$APP_ID" != "APP_ID" ]
    then
        echo "Downloading App with ID $APP_ID, titled: $TITLE..."
        apkeep -a $APP_ID . #-d google-play -o split_apk=true -u $EMAIL -p $PASSWORD .
    fi
done < apps-EDUCATION.csv # replace the csv file
```

This downloads a mixture of .apk and .xapk
<img width="609" alt="Screenshot 2023-07-06 at 9 24 58 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/98197696/17359f8b-c155-48a9-98cc-ce79c060552c">

Strangely, when I open the xapk files, (after renaming them to .zip), there is no .obb file
<img width="173" alt="Screenshot 2023-07-06 at 9 25 26 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/98197696/2f07a29d-4fd5-4e92-ab6b-e086bff5f814">

I am able to open the .apk with the API 33 Googe Pixel 6a fine, I have uploaded 10+ apps which worked in the Google Drive Folder (apps-that-work-6jul)

I'm still figuring out why this is the case and how to fix this, but the apps that are downloaded are evidently under arm architecture
<img width="217" alt="Screenshot 2023-07-06 at 9 29 03 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/98197696/91e30c8b-ee15-4d72-b759-ac15a50d5a2f">

**Comment by SebastianZimmeck** [comment]
OK, I do not know the details of the downloaders we use, but [with Raccoon you can specify a particular device](https://raccoon.onyxbits.de/apk-downloader-v4/setup/#the-gsf-id-and-the-useragent-string) and all APKs, XAPKs, etc. are compatible with it (because the Google Play Store thinks that this particular device is performing the download). So, maybe try Raccoon (unless there is a reason speaking against it).

**Comment by wesley-tan** [comment]
So, there are two solutions. I'm still checking through whether it works for most apps but so far it works for the few apps (about 10 per method) that I tried.

Method 1: Raccoon

This involves searching for the application in Raccoon itself. Using the app id found in the .csv files, we just simply search for it in Raccoon and pick the appropriate app. This is slow because the process is manual (have yet to find a way to automate the Raccoon process, and it may be confusing trying to see which app you want since Raccoon doesn't really have a way to search by the app id itself (it does a more generic search similar to a search engine etc) 

<img width="1177" alt="Screenshot 2023-07-09 at 5 10 18 PM" src="https://github.com/privacy-tech-lab/gpc-android/assets/98197696/ab336466-f488-44c7-bc74-c6125991ec47">

Then, I used the following code to process the split apks in the Racoon folder

```
#!/bin/bash

# Directory containing folders with APK files
APK_PARENT_DIR="/Users/wesleysimeontan/Raccoon/content/apps"

# Device ID
DEVICE_ID="emulator-5554"

# Function to install split APKs
install_split_apks() {
    local apk_dir="$1"
    echo "Installing APKs from $apk_dir..."

    # Find all split APK files within the directory
    local apks=$(find "$APK_PARENT_DIR/$apk_dir" -name "*.apk")

    # Install the APKs using adb
    adb -s $DEVICE_ID install-multiple $apks
}

# Ensure ADB is connected and can see your device
adb devices

# Main script execution

# Get all subdirectories in the parent directory
app_dirs=$(ls -d "$APK_PARENT_DIR"/*/)

# Install each set of split APKs
for apk_dir in $app_dirs; do
    # Extract the directory name from the path
    apk_dir=$(basename "$apk_dir")

    # Install the APKs
    install_split_apks "$apk_dir"
done
```

Basically, this installs the apks into the phone. As of typing this, I tried about 10 apps including Duolinguo and this seems to work. 

Method 2: Working with the xapk files

```

#!/bin/bash

# Directory containing XAPK files
XAPK_DIR="/Users/wesleysimeontan/Desktop/ptl-google-play-scraper/install-apps-here/apps-9-jul"

# Function to install an XAPK
install_xapk() {
    local device_id="emulator-5554"
    echo "Installing $xapk on device $device_id..."
    
    local temp_dir=$(mktemp -d -t xapk-XXXXXX)
    unzip "$XAPK_DIR/$xapk" -d "$temp_dir"
    local apks=$(find "$temp_dir" -name "*.apk")
    
    # Specify the target device
    adb -s $device_id install-multiple $apks
    rm -rf "$temp_dir"
}

# Main script execution

# Ensure ADB is connected and can see your device
adb devices

# Find all XAPK files in the XAPK directory
for xapk in $(ls "$XAPK_DIR"/*.xapk); do
    # Extract the filename from the path
    xapk=$(basename "$xapk")

    # Install the XAPK
    install_xapk "$xapk"
done
```

This seems to work for the few apps I downloaded but I think Method 1 may be more 'reliable' because you can guarantee it downloads in arm architecture. Think the problem why the previous ones may not have worked may be because of different in architecture.

Will continue to try more of the applications

**Comment by wesley-tan** [comment]
Have found a solution: 

First I used this as my `play-store-downloader.sh`

```
#!/bin/bash
EMAIL='<email>'  # replace with your email
PASSWORD='<password>'  # replace with your password

# Read the CSV file
while IFS=$',' read -r APP_ID TITLE DEVELOPER SCORE
do
    # Skip the header
    if [ "$APP_ID" != "APP_ID" ]
    then
        echo "Downloading App with ID $APP_ID, titled: $TITLE..."
        apkeep -a $APP_ID -d google-play -o split_apk=1 -u $EMAIL -p $PASSWORD .
    fi
done < apps-AUTO_AND_VEHICLES.csv # replace the csv file
```
This installed mixture of split apk and apk


Then, I use a `install-split-apk.sh`

```
#!/bin/bash

# Directory containing folders with APK files
APK_PARENT_DIR="/Users/wesleysimeontan/Desktop/ptl-google-play-scraper/install-apps-here/test-folder-workflow"

# Device ID
DEVICE_ID="emulator-5554"

# Function to install split APKs
install_split_apks() {
    local apk_dir="$1"
    echo "Installing APKs from $apk_dir..."

    # Find all split APK files within the directory
    local apks=$(find "$APK_PARENT_DIR/$apk_dir" -name "*.apk")

    # Install the APKs using adb
    adb -s $DEVICE_ID install-multiple $apks
}

# Ensure ADB is connected and can see your device
adb devices

# Main script execution

# Get all subdirectories in the parent directory
app_dirs=$(ls -d "$APK_PARENT_DIR"/*/)

# Install each set of split APKs
for apk_dir in $app_dirs; do
    # Extract the directory name from the path
    apk_dir=$(basename "$apk_dir")

    # Install the APKs
    install_split_apks "$apk_dir"
done
```

It will then show something like this and the adb would install the apk files in my Android virtual device
<img width="972" alt="Screenshot 2023-07-11 at 12 14 34 AM" src="https://github.com/privacy-tech-lab/gpc-android/assets/98197696/6066dd21-e4ad-44e5-ac52-ae5dc6d7a2cf">
(both the apk files from the split apk files and those that were already downloaded as apk files were downloaded)
All could be successfully opened (tried with another category as well)

**Comment by SebastianZimmeck** [comment]
OK, @wesley-tan, can you pass 15 or so apps to @n-aggarwal for testing on a real device?

**Comment by wesley-tan** [comment]
https://drive.google.com/drive/folders/1uYn7AnMs2SRPdcuxGV6oWIhhqcKLi7Vi?usp=drive_link

@n-aggarwal the files can be found here, tell me if there are any issues

**Comment by SebastianZimmeck** [comment]
@wesley-tan will close this issue once @n-aggarwal is able to run the test set apps.

**Comment by n-aggarwal** [comment]
All the apps in the "apps-that-work" folder work! I have also integrated the `install_split_apks` function in my script to automate the installation!

**Comment by wesley-tan** [comment]
> All the apps in the "apps-that-work" folder work! I have also integrated the `install_split_apks` function in my script to automate the installation!

Great :)) I will start downloading the apps and placing in the google drive, I'll categorize them by cateogry and document when and how I download them

**Comment by n-aggarwal** [comment]
@SebastianZimmeck do we want to revise the app list as you mentioned in #78? If so, then perhaps @wesley-tan you should wait before downloading the apps!

**Comment by SebastianZimmeck** [comment]
Good point, @n-aggarwal! I commented [there](https://github.com/privacy-tech-lab/gpc-android/issues/78#issuecomment-1633260569).
